# Generated by Django 2.1.11 on 2019-08-31 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 21, 33, 4, 983423), verbose_name='Request date'),
        ),
    ]
