# Generated by Django 2.1.11 on 2019-08-31 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 15, 7, 52, 560427), verbose_name='Request date'),
        ),
        migrations.AlterField(
            model_name='user_request',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Cancelled'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
