# Generated by Django 2.1.11 on 2019-08-31 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='area',
            field=models.CharField(choices=[('CB', 'CIENCIAS BASICAS Y AMBIENTALES'), ('SA', 'CIENCIAS DE LA SALUD'), ('SH', 'CIENCIAS SOCIALES Y HUMANIDADES'), ('NG', 'ECONOMIA Y NEGOCIOS'), ('IN', 'INGENIERIAS')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user_request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 17, 22, 51, 427102), verbose_name='Request date'),
        ),
    ]
