# Generated by Django 2.1.11 on 2019-09-07 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190906_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='degree',
            field=models.CharField(choices=[('EP', 'EDUCACION PRIMARIA'), ('ES', 'EDUCACION SECUNDARIA'), ('BA', 'BACHILLER'), ('GR', 'GRADO'), ('PG', 'POST-GRADO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 16, 46, 51, 988341), verbose_name='Request date'),
        ),
    ]
